### ISSUE TITLE
.CSV (version 2) are not loaded

### ISSUE THREAD

**Issue by frapaezla** [dwaithe/FCSfitJS#1]
Dear Dominic,

I noticeced that when trying to load .csv(versoin 2)  they are opened but they are not loaded into the interface. This is not the case for .SIN files that are even  automatically plotted. Attached the .csv(v2)  file that I tried in the program.

Thank you for your help

[CorrelationFocusPoint.csv](https://github.com/dwaithe/FCSfitJS/files/7409688/CorrelationFocusPoint.csv)

**Comment by dwaithe** [comment]
Hi frapaezla,
Sorry for the delay. I had a look at your .csv and there was a \r after the 'end' statement. This was causing a problem. Not sure why it was there in the file? Might just be a linux versus Windows thing. In either case I have made the software robust so that this won't effect it anymore. I have updated the fix to the online branch. You might need to clear your web history (cache) before the changes have an effect. Here is screenshot of your data working online:
![Screenshot 2021-11-12 at 15 24 08](https://user-images.githubusercontent.com/4719022/141491450-b1a2eec3-8716-4e05-b7f4-af3eb21660f6.png)
Thanks for using the software!
